CREATE TABLE STUDENT 
   (	"ID" NUMBER, 
	"FULL_NAME" VARCHAR2(50 BYTE), 
	"BIRTHDAY" DATE, 
	"CLASS_NAME" VARCHAR2(20 BYTE), 
	"MAJOR" VARCHAR2(20 BYTE), 
	"HOMETOWN" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"AVERAGE_MARK" FLOAT(126)
   )